name: Download Dependencies and Run Script

on:
  push:
    branches:
      - pre-publish
      - test-auto-upload

env:
  APP_ID: ${{ secrets.APP_ID }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  TOOL_ID: ${{ secrets.TOOL_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache dependencies
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      
      - name: Install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Delete Old Package
        run: rm -rf ./dist/build/*

      - name: Run unit tests && Run Script
        run: yarn build:mp-alipay
        
      - name: Deploy
        run: yarn deploy