name: Download Dependencies and Run Script

on:
  push:
    branches:
      - pre-publish
      - test-auto-upload

env:
  APP_ID: ${{ secrets.APP_ID }}
  PRIVATE_KEY: -----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCaNCf9KsXaWWhmYUIet37teJI6vMXK93C750s26HglyjKKQ9K6YkRMDvPZXjgVAri+bD0UJwFB0lgAx3dVyjt8EDdbMSyUGywsFLlP6mdrpIgpJ95moW+vTCd8W6W8LTyCfBsAZfj5izKrepre+UeELAFmFkvDaqdLTBTGLhoNApVqpNmEluWC9uNRPv9JzWLU/9Bv+weJ/3NK+u9OdevPL2OgahBfSu0/NFWYEh06zRZyh9TCrTwuAkeM90v7laTVGK1kbKkfYd+R3/J0RV/5QE6tCRJSsp3k8qAMDbqPARHu5f5sfx6i2Y9d6Z627mL5nBYRBwhf63zFo5aPEbsBAgMBAAECggEBAJRXtFiB+0/wTtSen4L5Nyuvn8zNqOF2ZIb/HIY34M1J1JDaajBPNDCO+dqUHxNnSN43NhLa6wStG2e0e4KWR98zom0hwya/dSD61sKgVtlgsHQXHIZSqyRR+HJTn/6E7f8A8ODTOE6nsBjym2YBHOFzi+zvafcV9NYk3J9B3mHAIayr4FkEx3MF9Dyv+QJwEUZwjRssqFH04tIwUS2E5ODuRy0MB4+TS76jEZgtrVKzlzmU/h91UzqlP04DVLYQrR29oe6qJ60ui9yeI+mBGG5pL7PoYhN0Upi4ny2heh/1KylSfo2NocoQiVODz8oBMuj6MDaaIxfYcmuTYZmEqgECgYEA9X+iFErWgblOJI9tQTl8/CwFKGXhKN0NzxOZ1XUPz6xIxhzr4zW2F66VeNo2tEPMF9fQECRdKXrJsSIDCXbRA6jJF1krfp3Rsd4bE7j7VyZ6B7J5ufogY4+jf8ka/EikrpbGvGzWy2NiEyd1TvgP0TgmMfX3MkGld6lXvqODNFECgYEAoMzJPJn5K5lVS9NJbohWwLqHiMAJuis+6xOHQZo5korBnYZGBFCsM4aan0Svju/3o6801V7M3dLytMLUWWoRjCNLIQSzVJeUFrDHzLI41ZbwrURhRkDAIs94GvMGuNgarRLC9mheoRj60DE8asgEkGYWCIy/QJ4qboFneYBI37ECgYEAvAsKhA6a5fyhfWGbJyW4tZOmU75NzDYeOKpj39vtw33MtGs8x+nBU7x3Y32J/2Qa9XxqM6MW9QnHafWKa/pluS7U8RxtM2wBTgO5q866PpQLTtAHa0vK+VfxvZS2Jd4ivlRhX7zifiHe4psLwPRDcVdX8lbcBNPBwbmlqzGl8zECgYBh6E8fdyEgStyErsGna5xm/SxJN6S0lmBZAir45s7nS1VYdMltFzHCrdK35zp97d7661NgF7jl1+uv5HEngE3u5g54rEQE3cZtinYdTOcOJjmlRl10STiz+V9ICXGuWubjOuk635G+xVbyLQh8fA1LXt1Ll2dcEPIFFwXKFTJKAQKBgHhPtUcOIlpdA9XtZ6KjtNpB+0uGZ1oqwXIj6ODcNesMijdTzToutLC5G8H2b5jBT0ZAxL6vUh1wq5RYJXP7BPELCudjmy64qTSmjAU57ZM5sVNYgo4h0xVV5BQAo3+GKNYplxS85nryw5MdQQRrrO58AI2lNSApO2a1ju/QRqGv\n-----END PRIVATE KEY-----\n
  TOOL_ID: ${{ secrets.TOOL_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Install
        run: yarn install --frozen-lockfile

      - name: Delete Old Package
        run: rm -rf ./dist/build/*

      - name: Run unit tests && Run Script
        run: yarn build:mp-alipay
        
      - name: Deploy
        run: yarn deploy